[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2018"

[features]
default = ["cli", "fs", "layout-cache"]
cli = ["anyhow", "codespan-reporting", "fs", "pico-args", "same-file"]
fs = ["dirs", "memmap2", "same-file", "walkdir"]
layout-cache = ["rand"]

[profile.dev]
# Faster compilation
debug = 0

[profile.dev.package."*"]
# Faster test execution
opt-level = 2

[dependencies]
fxhash = "0.2.1"
image = { version = "0.23", default-features = false, features = ["png", "jpeg"] }
itertools = "0.10"
miniz_oxide = "0.4"
pdf-writer = { git = "https://github.com/typst/pdf-writer", rev = "27b207a" }
rustybuzz = "0.4"
serde = { version = "1", features = ["derive", "rc"] }
ttf-parser = "0.12"
unicode-bidi = "0.3.5"
unicode-segmentation = "1.8"
unicode-xid = "0.2"
xi-unicode = "0.3"
anyhow = { version = "1", optional = true }
codespan-reporting = { version = "0.11", optional = true }
dirs = { version = "3", optional = true }
memmap2 = { version = "0.3", optional = true }
pico-args = { version = "0.4", optional = true }
rand = { version = "0.8", optional = true }
same-file = { version = "1", optional = true }
walkdir = { version = "2", optional = true }

[dev-dependencies]
filedescriptor = "0.8"
iai = { git = "https://github.com/reknih/iai" }
tiny-skia = "0.6"
usvg = { version = "0.15", default-features = false }
walkdir = "2"

[[bin]]
name = "typst"
required-features = ["cli"]

[[test]]
name = "typeset"
required-features = ["fs"]
harness = false

[[bench]]
name = "oneshot"
path = "benches/oneshot.rs"
harness = false
