[package]
name = "typstc"
version = "0.1.0"
authors = ["Laurenz Mädje <laurmaedje@gmail.com>"]
edition = "2018"

[dependencies]
tide = { path = "../tide" }
toddle = { path = "../toddle" }
byteorder = "1"
smallvec = "0.6.10"
unicode-xid = "0.1.0"

[[bin]]
name = "typst-bin"
path = "src/bin/main.rs"

[[test]]
name = "layouting"
path = "tests/layouting.rs"
harness = false
