[package]
name = "typstc"
version = "0.1.0"
authors = ["Laurenz Mädje <laurmaedje@gmail.com>"]
edition = "2018"

[dependencies]
fontdock = { path = "../fontdock", features = ["serialize"] }
tide = { path = "../tide" }
byteorder = "1"
smallvec = "1"
unicode-xid = "0.2"
async-trait = "0.1"
ttf-parser = "0.8.2"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", optional = true }
futures-executor = { version = "0.3", optional = true }

[features]
default = ["fs", "futures-executor", "serde_json"]
fs = ["fontdock/fs"]

[[bin]]
name = "typst"
path = "src/bin/main.rs"
required-features = ["futures-executor"]

[[test]]
name = "typeset"
path = "tests/src/typeset.rs"
harness = false
required-features = ["futures-executor", "serde_json"]
