[package]
name = "typstc"
version = "0.1.0"
authors = ["Laurenz Mädje <laurmaedje@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
toddle = { path = "../toddle", default-features = false }
tide = { path = "../tide" }
byteorder = "1"
smallvec = "1"
unicode-xid = "0.2"
async-trait = "0.1"
futures-executor = { version = "0.3", optional = true }

[features]
default = ["fs-provider", "futures-executor"]
fs-provider = ["toddle/fs-provider"]

[[bin]]
name = "typst"
path = "src/bin/main.rs"
required-features = ["futures-executor"]

[[test]]
name = "layouter"
path = "tests/src/layouter.rs"
harness = false
required-features = ["futures-executor"]

[[test]]
name = "parser"
path = "tests/src/parser.rs"
harness = false
