[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2021"

[workspace]
members = ["cli", "library", "macros"]

[dependencies]
typst-macros = { path = "macros" }
bitflags = "1"
bytemuck = "1"
comemo = "0.1"
flate2 = "1"
image = { version = "0.24", default-features = false, features = ["png", "jpeg", "gif"] }
miniz_oxide = "0.5"
once_cell = "1"
pdf-writer = "0.6"
pixglyph = { git = "https://github.com/typst/pixglyph" }
regex = "1"
resvg = { version = "0.22", default-features = false }
rex = { git = "https://github.com/laurmaedje/ReX" }
roxmltree = "0.14"
rustybuzz = "0.5"
serde = { version = "1", features = ["derive"] }
siphasher = "0.3"
subsetter = "0.1"
svg2pdf = "0.4"
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
tiny-skia = "0.6.2"
ttf-parser = "0.17"
unicode-segmentation = "1"
unicode-xid = "0.2"
unscanny = "0.1"
usvg = { version = "0.22", default-features = false }

[dev-dependencies]
typst-library = { path = "library" }
iai = { git = "https://github.com/reknih/iai" }
elsa = "1.7"
walkdir = "2"

[profile.dev]
debug = 0

[profile.dev.package."*"]
opt-level = 2

[[test]]
name = "typeset"
harness = false

[[bench]]
name = "oneshot"
harness = false
