[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2021"

[dependencies]
# Workspace
typst-macros = { path = "./macros" }

# Utilities
bitflags = "1"
bytemuck = "1"
fxhash = "0.2"
once_cell = "1"
serde = { version = "1", features = ["derive"] }
typed-arena = "2"
unscanny = "0.1"
regex = "1"

# Incremental compilation
comemo = { git = "https://github.com/typst/comemo" }

# Text and font handling
hypher = "0.1"
kurbo = "0.8"
ttf-parser = "0.17"
rustybuzz = "0.5"
unicode-bidi = "0.3.5"
unicode-segmentation = "1"
unicode-xid = "0.2"
unicode-script = "0.5"
xi-unicode = "0.3"

# Raster and vector graphics handling
image = { version = "0.24", default-features = false, features = ["png", "jpeg", "gif"] }
usvg = { version = "0.22", default-features = false }

# External implementation of user-facing features
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
rex = { git = "https://github.com/laurmaedje/ReX" }
lipsum = { git = "https://github.com/reknih/lipsum" }
csv = "1"
serde_json = "1"

# PDF export
miniz_oxide = "0.5"
pdf-writer = "0.6"
subsetter = { git = "https://github.com/typst/subsetter" }
svg2pdf = "0.4"

# Raster export / rendering
tiny-skia = "0.6.2"
pixglyph = { git = "https://github.com/typst/pixglyph" }
resvg = { version = "0.22", default-features = false }
roxmltree = "0.14"
flate2 = "1"

# Command line interface / tests
pico-args = { version = "0.4", optional = true }
codespan-reporting = { version = "0.11", optional = true }
same-file = { version = "1", optional = true }
walkdir = { version = "2", optional = true }
elsa = { version = "1.7", optional = true }
dirs = { version = "4", optional = true }
memmap2 = { version = "0.5", optional = true }
siphasher = { version = "0.3", optional = true }
notify = { version = "5", optional = true }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"], optional = true }

[dev-dependencies]
iai = { git = "https://github.com/reknih/iai" }
walkdir = "2"

[features]
default = ["tests"]
tests = ["same-file", "walkdir", "elsa", "siphasher"]
cli = [
    "pico-args",
    "codespan-reporting",
    "dirs",
    "memmap2",
    "same-file",
    "walkdir",
    "elsa",
    "siphasher",
    "notify",
    "chrono",
]

[profile.dev]
# Faster compilation
debug = 0

[profile.dev.package."*"]
# Faster test execution
opt-level = 2

[[bin]]
name = "typst"
required-features = ["cli"]

[[test]]
name = "typeset"
required-features = ["tests"]
harness = false

[[bench]]
name = "oneshot"
path = "benches/oneshot.rs"
harness = false
