[package]
name = "typstc"
version = "0.1.0"
authors = ["Laurenz Mädje <laurmaedje@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1"
fontdock = { path = "../fontdock", features = ["fs", "serialize"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
smallvec = "1"
tide = { path = "../tide" }
ttf-parser = "0.8.2"
unicode-xid = "0.2"
futures-executor = { version = "0.3", optional = true }

[[bin]]
name = "typst"
path = "src/bin/main.rs"
required-features = ["futures-executor"]

[[test]]
name = "typeset"
path = "tests/src/typeset.rs"
harness = false
required-features = ["futures-executor"]
