[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2018"

[features]
default = ["fs"]
fs = ["fontdock/fs"]
cli = ["fs", "anyhow"]
# serde = []

[workspace]
members = ["bench"]

[profile.dev]
# Faster compilation
debug = 0

[profile.dev.package."*"]
# Faster test execution
opt-level = 2

[dependencies]
fontdock = { path = "../fontdock", default-features = false }
image = { version = "0.23", default-features = false, features = ["jpeg", "png"] }
miniz_oxide = "0.3"
pdf-writer = { path = "../pdf-writer" }
rustybuzz = { git = "https://github.com/laurmaedje/rustybuzz" }
ttf-parser = "0.12"
unicode-bidi = "0.3"
unicode-xid = "0.2"
xi-unicode = "0.3"
anyhow = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
walkdir = "2"
tiny-skia = "0.5"
usvg = { version = "0.14", default-features = false }

[[bin]]
name = "typst"
required-features = ["cli"]

[[test]]
name = "typeset"
required-features = ["fs"]
harness = false
