[package]
name = "typstc"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2018"

[workspace]
members = ["main"]

[dependencies]
async-trait = "0.1"
fontdock = { path = "../fontdock", features = ["fs", "serialize"] }
serde = { version = "1", features = ["derive"], optional = true }
tide = { path = "../tide" }
ttf-parser = "0.8.2"
unicode-xid = "0.2"

[features]
serialize = []

[dev-dependencies]
futures-executor = "0.3"
serde_json = "1"

[[test]]
name = "typeset"
path = "tests/src/typeset.rs"
harness = false
required-features = ["serialize"]
