[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2018"

[features]
default = ["fs", "anyhow"]
fs = ["fontdock/fs"]

[dependencies]
fontdock = { path = "../fontdock", default-features = false }
pdf-writer = { path = "../pdf-writer" }
itoa = "0.4"
ttf-parser = "0.8.2"
unicode-xid = "0.2"

# feature = "serde"
serde = { version = "1", features = ["derive"], optional = true }
anyhow = { version = "1", optional = true }

[dev-dependencies]
criterion = "0.3"
memmap = "0.7"
raqote = { version = "0.8", default-features = false }

[profile.dev.package."*"]
opt-level = 2

[profile.release]
lto = true

[lib]
bench = false

[[bin]]
name = "typst"
required-features = ["fs", "anyhow"]

[[test]]
name = "typeset"
required-features = ["fs"]
harness = false

[[bench]]
name = "benchmarks"
required-features = ["fs"]
harness = false
