[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2018"

[features]
default = ["fs"]
cli = ["fs", "anyhow"]
fs = ["fontdock/fs"]

[workspace]
members = ["bench"]

[profile.dev]
# Faster compilation
debug = 0

[profile.dev.package."*"]
# Faster test execution
opt-level = 2

[dependencies]
fontdock = { path = "../fontdock", default-features = false }
image = { version = "0.23", default-features = false, features = ["jpeg", "png"] }
miniz_oxide = "0.3"
pdf-writer = { path = "../pdf-writer" }
ttf-parser = "0.8.2"
unicode-xid = "0.2"
anyhow = { version = "1", optional = true }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
tiny-skia = "0.2"
walkdir = "2"

[[bin]]
name = "typst"
required-features = ["cli"]

[[test]]
name = "typeset"
required-features = ["fs"]
harness = false
