[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2021"

[features]
default = ["fs", "layout-cache"]
cli = ["fs", "pico-args", "codespan-reporting", "same-file"]
fs = ["dirs", "memmap2", "same-file", "walkdir"]
layout-cache = []

# Dependency updates:
# - Bump ttf-parser when rustybuzz is updated
# - Bump usvg and resvg in conjunction with svg2pdf

[dependencies]
# Workspace
typst-macros = { path = "./macros" }

# Utilities
bytemuck = "1"
fxhash = "0.2"
itertools = "0.10"
once_cell = "1"
serde = { version = "1", features = ["derive"] }

# Text and font handling
ttf-parser = "0.12"
rustybuzz = "0.4"
unicode-bidi = "0.3.5"
unicode-segmentation = "1"
unicode-xid = "0.2"
xi-unicode = "0.3"

# Raster and vector graphics handling
image = { version = "0.23", default-features = false, features = ["png", "jpeg"] }
usvg = { version = "0.20", default-features = false }

# External implementation of user-facing features
syntect = { version = "4.6", default-features = false, features = ["dump-load", "parsing", "regex-fancy", "assets"] }

# PDF export
miniz_oxide = "0.4"
pdf-writer = "0.4"
svg2pdf = "0.2"

# Raster export / rendering
tiny-skia = "0.6.2"
pixglyph = { git = "https://github.com/typst/pixglyph" }
resvg = { version = "0.20", default-features = false }
roxmltree = "0.14"
flate2 = "1"

# Command line interface
pico-args = { version = "0.4", optional = true }
codespan-reporting = { version = "0.11", optional = true }
same-file = { version = "1", optional = true }

# File system loading
dirs = { version = "4", optional = true }
memmap2 = { version = "0.5", optional = true }
walkdir = { version = "2", optional = true }

# Still here for layout cache evaluation, but must be activated manually.
rand = { version = "0.8", optional = true }

[dev-dependencies]
filedescriptor = "0.8"
iai = { git = "https://github.com/reknih/iai" }
walkdir = "2"

[profile.dev]
# Faster compilation
debug = 0

[profile.dev.package."*"]
# Faster test execution
opt-level = 2

[[bin]]
name = "typst"
required-features = ["cli"]

[[test]]
name = "typeset"
required-features = ["fs"]
harness = false

[[bench]]
name = "oneshot"
path = "benches/oneshot.rs"
harness = false
