[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2021"

[workspace]
members = ["macros"]

[dependencies]
# Workspace
typst-macros = { path = "./macros" }

# Utilities
bitflags = "1"
bytemuck = "1"
comemo = "0.1"
once_cell = "1"
regex = "1"
serde = { version = "1", features = ["derive"] }
siphasher = "0.3"
typed-arena = "2"
unscanny = "0.1"

# Text and font handling
hypher = "0.1"
kurbo = "0.8"
rustybuzz = "0.5"
ttf-parser = "0.17"
unicode-bidi = "0.3.5"
unicode-script = "0.5"
unicode-segmentation = "1"
unicode-xid = "0.2"
xi-unicode = "0.3"

# Raster and vector graphics handling
image = { version = "0.24", default-features = false, features = ["png", "jpeg", "gif"] }
usvg = { version = "0.22", default-features = false }

# External implementation of user-facing features
csv = "1"
lipsum = { git = "https://github.com/reknih/lipsum" }
rex = { git = "https://github.com/laurmaedje/ReX" }
serde_json = "1"
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
unicode-math = { git = "https://github.com/s3bk/unicode-math/" }

# PDF export
miniz_oxide = "0.5"
pdf-writer = "0.6"
subsetter = "0.1"
svg2pdf = "0.4"

# Rendering
flate2 = "1"
pixglyph = { git = "https://github.com/typst/pixglyph" }
resvg = { version = "0.22", default-features = false }
roxmltree = "0.14"
tiny-skia = "0.6.2"

# Command line interface
chrono = { version = "0.4", default-features = false, features = ["clock", "std"], optional = true }
codespan-reporting = { version = "0.11", optional = true }
dirs = { version = "4", optional = true }
elsa = { version = "1.7", optional = true }
memmap2 = { version = "0.5", optional = true }
notify = { version = "5", optional = true }
pico-args = { version = "0.4", optional = true }
same-file = { version = "1", optional = true }
walkdir = { version = "2", optional = true }

[dev-dependencies]
iai = { git = "https://github.com/reknih/iai" }
elsa = "1.7"
walkdir = "2"

[features]
cli = [
    "chrono",
    "codespan-reporting",
    "dirs",
    "elsa",
    "memmap2",
    "notify",
    "pico-args",
    "same-file",
    "walkdir",
]

[profile.dev]
debug = 0 # Faster compilation

[profile.dev.package."*"]
opt-level = 2 # Faster test execution

[[bin]]
name = "typst"
required-features = ["cli"]

[[test]]
name = "typeset"
harness = false

[[bench]]
name = "oneshot"
harness = false
