[package]
name = "typstc"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2018"

[workspace]
members = ["main"]

[profile.dev.package."*"]
opt-level = 2

[dependencies]
arrayvec = "0.5"
fontdock = { path = "../fontdock" }
kurbo = "0.6"
tide = { path = "../tide" }
ttf-parser = "0.8.2"
unicode-xid = "0.2"
serde = { version = "1", features = ["derive"], optional = true }
smallvec = "1"

[features]
default = ["fs", "serialize"]
serialize = ["serde"]
fs = ["fontdock/fs"]

[dev-dependencies]
criterion = "0.3"
futures-executor = "0.3"
serde_json = "1"
raqote = { version = "0.8", default-features = false }

[[test]]
name = "typeset"
path = "tests/test_typeset.rs"
required-features = ["fs"]
harness = false

[[bench]]
name = "benchmarks"
path = "benches/benchmarks.rs"
required-features = ["fs"]
harness = false
