[package]
name = "typst"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2018"

[workspace]
members = ["bench"]

[features]
default = ["fs", "anyhow"]
fs = ["fontdock/fs"]

[dependencies]
fontdock = { path = "../fontdock", default-features = false }
pdf-writer = { path = "../pdf-writer" }
deflate = { version = "0.8.6" }
image = { version = "0.23", default-features = false, features = ["jpeg", "png"] }
itoa = "0.4"
ttf-parser = "0.8.2"
unicode-xid = "0.2"

# feature = "serde"
serde = { version = "1", features = ["derive"], optional = true }

# for the CLI
anyhow = { version = "1", optional = true }

[dev-dependencies]
memmap = "0.7"
tiny-skia = "0.2"

[profile.dev]
opt-level = 2

[profile.release]
lto = true

[[bin]]
name = "typst"
required-features = ["fs", "anyhow"]

[[test]]
name = "typeset"
required-features = ["fs"]
harness = false
