[package]
name = "typst-library"
version = "0.1.0"
authors = ["The Typst Project Developers"]
edition = "2021"

[lib]
test = false
doctest = false
bench = false

[dependencies]
typst = { path = ".." }
comemo = { git = "https://github.com/typst/comemo" }
csv = "1"
hypher = "0.1"
kurbo = "0.8"
lipsum = { git = "https://github.com/reknih/lipsum" }
once_cell = "1"
rex = { git = "https://github.com/laurmaedje/ReX" }
roxmltree = "0.14"
rustybuzz = "0.5"
serde_json = "1"
syntect = { version = "5", default-features = false, features = ["default-syntaxes", "regex-fancy"] }
ttf-parser = "0.17"
typed-arena = "2"
unicode-bidi = "0.3.5"
unicode-math = { git = "https://github.com/s3bk/unicode-math/" }
unicode-script = "0.5"
xi-unicode = "0.3"
