"CMU-SansSerif-Regular.ttf"      = ["Computer Modern", "Regular", "SansSerif"]
"CMU-SansSerif-Italic.ttf"       = ["Computer Modern", "Italic", "SansSerif"]
"CMU-SansSerif-Bold.ttf"         = ["Computer Modern", "Bold", "SansSerif"]
"CMU-SansSerif-Bold-Italic.ttf"  = ["Computer Modern", "Bold", "Italic", "SansSerif"]
"CMU-Serif-Regular.ttf"          = ["Computer Modern", "Regular", "Serif"]
"CMU-Serif-Italic.ttf"           = ["Computer Modern", "Italic", "Serif"]
"CMU-Serif-Bold.ttf"             = ["Computer Modern", "Bold", "Serif"]
"CMU-Serif-Bold-Italic.ttf"      = ["Computer Modern", "Bold", "Italic", "Serif"]
"CMU-Typewriter-Regular.ttf"     = ["Computer Modern", "Regular", "Serif", "SansSerif", "Monospace"]
"CMU-Typewriter-Italic.ttf"      = ["Computer Modern", "Italic", "Serif", "SansSerif", "Monospace"]
"CMU-Typewriter-Bold.ttf"        = ["Computer Modern", "Bold", "Serif", "SansSerif", "Monospace"]
"CMU-Typewriter-Bold-Italic.ttf" = ["Computer Modern", "Bold", "Italic", "Serif", "SansSerif", "Monospace"]
"Latin-Modern-Math.otf"          = ["Latin Modern", "Latin Modern Math", "Math", "Regular", "Serif"]
"NotoEmoji-Regular.ttf"          = ["Noto", "Noto Emoji", "Regular", "SansSerif", "Serif", "Monospace"]
