[package]
name = "typst"
description = "A new markup-based typesetting system that is powerful and easy to learn."
categories = ["compilers", "science"]
keywords = ["markup", "typesetting", "typst"]
version.workspace = true
rust-version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
doctest = false
bench = false

[dependencies]
typst-macros = { workspace = true }
typst-syntax = { workspace = true }
base64 = { workspace = true }
bitflags = { workspace = true }
bytemuck = { workspace = true }
comemo = { workspace = true }
ecow = { workspace = true}
flate2 = { workspace = true }
fontdb = { workspace = true }
image = { workspace = true }
indexmap = { workspace = true }
kurbo = { workspace = true }
lasso = { workspace = true }
log = { workspace = true }
miniz_oxide = { workspace = true }
once_cell = { workspace = true }
palette = { workspace = true }
pdf-writer = { workspace = true }
regex = { workspace = true }
roxmltree = { workspace = true }
rustybuzz = { workspace = true }
serde = { workspace = true }
siphasher = { workspace = true }
smallvec = { workspace = true }
subsetter = { workspace = true }
svg2pdf = { workspace = true }
time = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
ttf-parser = { workspace = true }
unicode-ident = { workspace = true }
unicode-math-class = { workspace = true }
unicode-properties = { workspace = true }
unicode-segmentation = { workspace = true }
unscanny = { workspace = true }
usvg = { workspace = true }
wasmi = { workspace = true }
xmp-writer = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
stacker = "0.1.15"
