name: Continuous integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust: [stable]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          path: typst

      - name: Checkout pdf-writer
        uses: actions/checkout@v2
        with:
          repository: typst/pdf-writer
          token: ${{ secrets.TYPSTC_ACTION_TOKEN }}
          path: pdf-writer

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --manifest-path typst/Cargo.toml --all-features

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path typst/Cargo.toml --all-features
